### ISSUE TITLE
Cannot find module '@jellybrick/wql-process-monitor' during npm run dev

### ISSUE THREAD

**Issue by Kintiru** [organization/alspotron#421]
# Description
pnpm이 설치되지 않은 환경에서 `npm install` 후 `npm run dev` 실행
pnpm 설치 후 'pnpm install` 이후에는 잘 작동함

# 예상되는 동작
9da07af 이후 pnpm 이 없어도 정상 작동

# 에러 메세지
```
[0] Error: Cannot find module '@jellybrick/wql-process-monitor'
[0] Require stack:
[0] - path\to\alspotron\dist\index.js
[0]     at Module._resolveFilename (node:internal/modules/cjs/loader:1084:15)
[0]     at n._resolveFilename (node:electron/js2c/browser_init:2:114728)
[0]     at Module._load (node:internal/modules/cjs/loader:929:27)
[0]     at l._load (node:electron/js2c/asar_bundle:2:13642)
[0]     at Module.require (node:internal/modules/cjs/loader:1150:19)
[0]     at require (node:internal/modules/cjs/helpers:119:18)
[0]     at new <anonymous> (path\to\alspotron\dist\index.js:126:297981)
[0]     at Object.<anonymous> (path\to\alspotron\dist\index.js:126:297408)
[0]     at Module._compile (node:internal/modules/cjs/loader:1271:14)
[0]     at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
```

# 버전
Windows 11 Pro 22H2 22621.2715
master branch
Node: 20.9.0
NPM: 10.2.4

# Comment
npm 으로 마이그레이션이 잘 이루어지지 않았을 수 있음
`npm install --include optional` 및 `npm install --include dev`로 명시적으로 설치해도 같음

**Comment by JellyBrick** [comment]
dev dependencies에서 node-gyp를 삭제하시고 `npm i`를 다시 실행하시면 됩니다.
